package config

import (
	"github.com/BurntSushi/toml"
	"io"
)

type AutoGenerated struct {
	Project struct {
		Install  []string `toml:"install"`
		LoppTime int      `toml:"lopp_time"`
		Log      struct {
			AccessLog string `toml:"access_log"`
			ErrorLog  string `toml:"error_log"`
		} `toml:"log"`
	} `toml:"project"`
	Plugin map[string]map[string]map[string]interface{} `toml:"plugin"`
	// 插件获取配置相关
	pluginName string
	scope      string
}

func (a *AutoGenerated) SetPluginName(name string) {
	a.pluginName = name
}

func (a *AutoGenerated) SetPluginScope(scope string) {
	a.scope = scope
}

func (a *AutoGenerated) PluginGetData(key string) interface{} {
	return a.Plugin[a.pluginName][a.scope][key]
}

// RangePluginData 遍历插件的配置
func (a *AutoGenerated) RangePluginData(fn func(k string, v interface{})) {
	for k, v := range a.Plugin[a.pluginName][a.scope] {
		fn(k, v)
	}
}

// 插件获取自身的对应的配置

func Read(reader io.Reader) *AutoGenerated {
	ag := &AutoGenerated{}
	_, err := toml.DecodeReader(reader, ag)
	if err != nil {
		panic(err)
	}
	return ag
}

func Write(writer io.Writer, cfg *AutoGenerated) error {
	return toml.NewEncoder(writer).Encode(cfg)
}
