package utils

import (
	"github.com/BurntSushi/toml"
	"github.com/mengzushan/bups/common/conf"
	"os"
	"path/filepath"
)

func GetConfig() *conf.AutoGenerated {
	return conf.InitConfig()
}

func SaveTomlConfig(tomlFile *conf.AutoGenerated) error {
	path, _ := os.Getwd()
	file, err := os.Create(path + filepath.FromSlash("/conf/dev/app.conf.toml"))
	if err != nil {
		panic(err)
	}
	return toml.NewEncoder(file).Encode(tomlFile)
}
