package utils

import (
	"github.com/BurntSushi/toml"
	"github.com/mengzushan/bups/common/conf"
	"os"
	"runtime"
)

func GetConfig() *conf.AutoGenerated {
	return conf.InitConfig()
}

func SaveTomlConfig(tomlFile *conf.AutoGenerated) error {
	path,_ := os.Getwd()
	file, err := os.Create(path + "/conf/dev/app.conf.toml")
	if err != nil {
		panic(err)
	}
	return toml.NewEncoder(file).Encode(tomlFile)
}

func PathRune() string {
	switch runtime.GOOS {
	case "windows":
		return "\\"
	default:
		return "/"
	}
}